name: SpaceFlares
author: Yukun
main: me.yukun.spaceflares.SpaceFlares
version: 1.1.0a
api-version: 1.20
softdepend: [ WorldGuard, Factions ]
description: >
  A plugin to give players flares that can summon falling loot boxes.
commands:
  spaceflares:
    description: Base command for SpaceFlares plugin.
    aliases: [ spaceflares, spaceflare, spacef, sflare, sf ]
  envoy:
    description: Base command for Envoy plugin.
    aliases: [ envoy, envoys ]