name: SpaceFlares
author: Yukun
main: me.yukun.spaceflares.SpaceFlares
version: ${project.version}
api-version: 1.21
softdepend: [ WorldGuard, Factions, CMI, DecentHolograms, SuperiorSkyblock2 ]
description: >
  A plugin to give players flares that can summon falling loot boxes.
commands:
  spaceflares:
    description: Base command for SpaceFlares plugin.
    aliases: [ spaceflares, spaceflare, spacef, sflare, sf ]
  envoy:
    description: Base command for Envoy plugin.
    aliases: [ envoy, envoys ]