name: SpaceFlares
author: Yukun
main: me.yukun.spaceflares.Main
version: 1.0.0b
api-version: 1.20
softdepend: [WorldGuard]
description: >
  A plugin to give players flares that can summon falling loot boxes.
commands:
  spaceflares:
    description: Base command for SpaceFlares plugin.
    aliases: [ spaceflares, spaceflare, spacef, sflare, sf ]